#:schema https://raw.githubusercontent.com/YunoHost/apps/main/schemas/manifest.v2.schema.json

packaging_format = 2

id = "openemr"
name = "OpenEMR"
description.en = "The most popular open source electronic health records and medical practice management solution."
description.fr = "La solution de gestion de dossiers de santé électroniques et de cabinet médical open source la plus populaire."

version = "7.0.3-3~ynh5"

maintainers = ["DeMiro5001"]

[upstream]
license = " GPL-3.0"
website = "https://www.open-emr.org"
demo = "https://www.open-emr.org/demo"
admindoc = "https://www.open-emr.org/wiki/index.php/OpenEMR_Wiki_Home_Page#Installation_Manuals"
userdoc = "https://www.open-emr.org/wiki/index.php/OpenEMR_Wiki_Home_Page#User_Manuals"
code = "https://github.com/openemr/openemr"

fund = "https://www.open-emr.org/donate/"

[integration]
yunohost = ">= 12.0.9"
helpers_version = "2.1"
architectures = "all"
multi_instance = true

ldap = false

sso = false

disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/openemr"

    [install.init_main_permission]
    type = "group"
    default = "all_users"

    [install.language]
    ask.en = "Choose the application language"
    ask.fr = "Choisissez la langue de l'application"
    type = "select"
    choices = ["fr", "en"]
    default = "fr"

    [install.admin]
    type = "user"

    [install.password]
    help.en = "Use the help field to add an information for the admin about this question."
    help.fr = "Utilisez le champ aide pour ajouter une information à l'intention de l'administrateur à propos de cette question."
    type = "password"

[resources]
    [resources.sources]

    [resources.sources.main]
    url = "https://github.com/openemr/openemr/archive/refs/tags/v7_0_3_3.tar.gz"
    sha256 = "a4ee83e1f95294af74807ac0a9a238d52e63cc0e42afdcac91c4bd2c00b994c4"
    autoupdate.strategy = "latest_github_tag"
    autoupdate.asset = "^v\d+_\d+_\d+_\d+$"

    [resources.system_user]

    [resources.install_dir]

    [resources.data_dir]

    [resources.permissions]
    main.url = "/"
    restricted.url = "/admin.php"
    restricted.additional_urls = ["/admin.php", "/acl_setup.php", "/acl_upgrade.php", "/sl_convert.php", "/sql_patch.php", "/sql_upgrade.php", "/gacl/setup.php", "/ippf_upgrade.php", "/tests", "/contrib/cqm_valueset", "/contrib/dsmiv", "/contrib/forms", "/contrib/portal_templates", "/contrib/util", "/contrib/venom"]
    restricted.allowed = "admins"
    restricted.show_tile = false

    [resources.apt]
    packages = "mariadb-server, php8.4-common, php8.4-mysql, php8.4-curl, php8.4-ldap, php8.4-xsl, php8.4-gd, php8.4-zip, php8.4-soap, php8.4-mbstring, php8.4-xml, php8.4-imagick, perl, libmagickwand-dev"

    [resources.database]
    type = "mysql"
