#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# INITIALIZE AND STORE SETTINGS
#=================================================

ynh_app_setting_set --key=php_max_input_vars --value=5000
ynh_app_setting_set --key=php_max_execution_time --value=600
ynh_app_setting_set --key=php_max_input_time --value=-1
ynh_app_setting_set --key=php_memory_limit --value=512M
ynh_app_setting_set --key=php_upload_max_filesize --value=250M
ynh_app_setting_set --key=php_post_max_size --value=250M

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Setting up source files..."

ynh_setup_source --dest_dir="$install_dir"

chown -R "$app:www-data" "$install_dir"

#=================================================
# APP INITIAL CONFIGURATION
#=================================================
ynh_script_progression "Adding $app's configuration files..."

#ynh_config_add --template="some_config_file" --destination="$install_dir/some_config_file"

#chmod 400 "$install_dir/some_config_file"
#chown "$app:$app" "$install_dir/some_config_file"

ynh_nodejs_install
ynh_composer_install

pushd $install_dir
  ynh_hide_warnings ynh_composer_exec install --no-dev
  ynh_hide_warnings npm install --loglevel=error 
  ynh_hide_warnings npm run build --loglevel=error
  php -f $install_dir/contrib/util/installScripts/InstallerAuto.php no_root_db_access=1 iuser=$admin iuserpass="$password" login=$db_user pass=$db_pwd dbname=$db_name
popd

chown -R "$app:www-data" "$install_dir"

#=================================================
# SYSTEM CONFIGURATION
#=================================================
ynh_script_progression "Adding system configurations related to $app..."

ynh_config_add_phpfpm

ynh_config_add_nginx

# Create a dedicated systemd config
ynh_config_add_systemd

ynh_config_add_logrotate

#ynh_config_add_fail2ban --logpath="/var/log/nginx/${domain}-error.log" --failregex="Regex to match into the log for a failed login"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Installation of $app completed"
