#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# ENSURE DOWNWARD COMPATIBILITY
#=================================================
ynh_script_progression "Ensuring downward compatibility..."

ynh_app_setting_set --key=php_max_input_vars --value=5000
ynh_app_setting_set --key=php_max_execution_time --value=600
ynh_app_setting_set --key=php_max_input_time --value=-1
ynh_app_setting_set --key=php_memory_limit --value=512M
ynh_app_setting_set --key=php_upload_max_filesize --value=250M
ynh_app_setting_set --key=php_post_max_size --value=250M

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Upgrading source files..."

ynh_setup_source --dest_dir="$install_dir" --full_replace

chown -R "$app:www-data" "$install_dir"

ynh_nodejs_install
ynh_composer_install

pushd $install_dir
  ynh_composer_exec install --no-dev
  ynh_hide_warnings npm install --loglevel=error
  ynh_hide_warnings npm run build --loglevel=error
  ynh_safe_rm $install_dir/setup.php
popd

chown -R "$app:www-data" "$install_dir"

#=================================================
# REAPPLY SYSTEM CONFIGURATION
#=================================================
ynh_script_progression "Upgrading system configurations related to $app..."

ynh_config_add_phpfpm

ynh_config_add_nginx

ynh_config_add_logrotate

#ynh_config_add_fail2ban --logpath="/var/log/nginx/${domain}-error.log" --failregex="Regex to match into the log for a failed login"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Upgrade of $app completed"
